spring:
  profiles:
    active: stage

---

spring:
  profiles: dev

message.response:   Hello from DEV spring boot properties

kafka.broker: localhost:9092
enable.auto.commit: false
auto.commit.interval.ms:  100
group.id: group1
kafka.auto.offset.reset: earliest
kafka.topic: my-topic
server.port: 8081


---

spring:
  profiles: stage

message.response:   Hello from STAGE spring boot properties
kafka.broker: localhost:9092
enable.auto.commit: false
auto.commit.interval.ms:  100
group.id: group1
kafka.auto.offset.reset: earliest
kafka.topic: my-topic


---

spring:
  profiles: prod

message.response:   Hello from PROD spring boot properties
kafka.broker: 10.113.0.137:9092,10.113.0.137:9093,10.113.0.137:9094
enable.auto.commit: false
auto.commit.interval.ms:  100
group.id: group1
kafka.auto.offset.reset: earliest
kafka.topic: my-topic
